### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to com.jsoniter.any.Any

### ISSUE THREAD

**Issue by siom79** [networknt/light-codegen#163]
I have the following OpenAPI definition:
```
openapi: 3.0.0

info:
  title: Example API
  description: The API of the Example service.
  version: 0.0.1
  
servers:
  - url: /example/v1
    
components:
  schemas:
    Person:
      properties:
        personId:
          type: string
      required:  
        - personId
        
paths:
  /persons/{personId}:
    get:
      summary: Returns the requested person.
      description: Returns the person given by the parameter personId.
      parameters:
        - name: personId
          in: path
          required: true
          description: ID of the person
          schema:
            type: string
      responses:
        '200':
          description: Returns the requested person.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Person'
        '400':
          description: The specified ID is invalid.
        '404':
          description: A person with the specified ID was not found.
        default:
          description: Unexpected error
```
I run the following command:
```
java -jar codegen-cli.jar -f openapi -o output  -c config.json -m example-openapi-v1.yml
```
This produces the following error:
```
16:51:11.413 [main] INFO com.fizzed.rocker.runtime.RockerRuntime - Rocker template reloading not activated
java.lang.ClassCastException: java.lang.String cannot be cast to com.jsoniter.any.Any
        at com.networknt.codegen.rest.OpenApiGenerator.injectEndpoints(OpenApiGenerator.java:348)
        at com.networknt.codegen.rest.OpenApiGenerator.generate(OpenApiGenerator.java:134)
        at com.networknt.codegen.Cli.run(Cli.java:98)
        at com.networknt.codegen.Cli.main(Cli.java:50)
```
Any ideas?

**Comment by stevehu** [comment]
@siom79 The Restful generator supports only the JSON format for the model. Could you please convert the yaml specification to json from https://editor.swagger.io/ and try it again? Let me know if you encounter other issues. Thanks.

**Comment by stevehu** [comment]
This is an old issue and it should be addressed once we have the capacity. https://github.com/networknt/light-codegen/issues/145

**Comment by siom79** [comment]
```
{
	"components":{
		"schemas":{
			"Person":{
				"properties":{
					"personId":{
						"type":"string"
					}
				},
				"required":[
					"personId"
				]
			}
		}
	},
	"info":{
		"description":"TheAPIoftheExampleservice.",
		"title":"ExampleAPI",
		"version":"0.0.1"
	},
	"openapi":"3.0.0",
	"paths":{
		"/persons/{personId}":{
			"get":{
				"description":"ReturnsthepersongivenbytheparameterpersonId.",
				"parameters":[
					{
						"description":"IDoftheperson",
						"in":"path",
						"name":"personId",
						"required":true,
						"schema":{
							"type":"string"
						}
					}
				],
				"responses":{
					"200":{
						"content":{
							"application/json":{
								"schema":{
									"$ref":"#/components/schemas/Person"
								}
							}
						},
						"description":"Returnstherequestedperson."
					},
					"400":{
						"description":"ThespecifiedIDisinvalid."
					},
					"404":{
						"description":"ApersonwiththespecifiedIDwasnotfound."
					},
					"default":{
						"description":"Unexpectederror"
					}
				},
				"summary":"Returnstherequestedperson."
			}
		}
	},
	"servers":[
		{
			"url":"/example/v1"
		}
	]
}
```

**Comment by charbull** [comment]
Hello @stevehu ,

I converted to json format and having the following issue:
```
C:\Users\Downloads\light-codegen-1.5.11\codegen-cli\target>java -jar codegen-cli.jar -o C:\\OLGAAAS -f openapi -m Ontology.json -c config.json
openapi Ontology.json config.json C:\\OLGAAAS
17:19:39.017 [main] INFO com.networknt.config.Config - daily config cache refresh
17:19:39.023 [main] INFO com.networknt.config.Config - Unable to load config from externalized folder for service.yml in
17:19:39.024 [main] INFO com.networknt.config.Config - Trying to load config from classpath directory for file service.yml
17:19:39.025 [main] INFO com.networknt.config.Config - Config loaded from default folder for service.yml
17:19:39.121 [main] INFO com.fizzed.rocker.runtime.RockerRuntime - Rocker version 0.22.0
17:19:39.122 [main] INFO com.fizzed.rocker.runtime.RockerRuntime - Rocker template reloading not activated
java.lang.NullPointerException
        at com.networknt.codegen.rest.OpenApiGenerator.injectEndpoints(OpenApiGenerator.java:353)
        at com.networknt.codegen.rest.OpenApiGenerator.generate(OpenApiGenerator.java:132)
        at com.networknt.codegen.Cli.run(Cli.java:91)
        at com.networknt.codegen.Cli.main(Cli.java:48)
A project has been generated successfully in C:\\OLGAAAS folder. Have fun!!!
```

Any suggestions? my json file is below
```
{
  "openapi" : "3.0.0",
  "servers" : [ {
    "description" : "OLGA as a service",
    "url" : "https://virtserver.swaggerhub.com/Ontology/OLGAsaas/1.0.0"
  } ],
  "info" : {
    "description" : "OLGA as a Service",
    "version" : "1.0.0",
    "title" : "OLGAas",
    "contact" : {
      "email" : "charbel.el-kaed@schneider-electric.com"
    },
    "license" : {
      "name" : "MIT",
      "url" : "https://github.com/EcoStruxure/OLGA/blob/master/LICENSE.TXT"
    }
  },
  "tags" : [ {
    "name" : "admins",
    "description" : "Secured Admin-only calls"
  }, {
    "name" : "users",
    "description" : "Operations available to regular users"
  } ],
  "paths" : {
    "/1.0/generate" : {
      "post" : {
        "tags" : [ "users" ],
        "summary" : "Requests Generation of Code based on an ontology model",
        "operationId" : "generate",
        "description" : "By passing in the appropriate options, you can generate a library fr CSharp, Java or Python om your ontology model",
        "parameters" : [ {
          "in" : "query",
          "name" : "parameters",
          "description" : "Options for the code generation",
          "required" : true,
          "schema" : {
            "$ref" : "#/components/schemas/olgaInput"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OLGA Generated Llibrary Successfully",
            "content" : {
              "application/octet-stream" : {
                "schema" : {
                  "type" : "string",
                  "format" : "binary"
                }
              }
            }
          },
          "400" : {
            "description" : "invalid input, object invalid"
          }
        },
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "string",
                "format" : "binary"
              }
            },
            "text/turtle" : {
              "schema" : {
                "type" : "string",
                "format" : "binary"
              }
            },
            "text/n3" : {
              "schema" : {
                "type" : "string",
                "format" : "binary"
              }
            },
            "application/rdf+xml" : {
              "schema" : {
                "type" : "string",
                "format" : "binary"
              }
            },
            "application/n-triples" : {
              "schema" : {
                "type" : "string",
                "format" : "binary"
              }
            },
            "application/n-quads" : {
              "schema" : {
                "type" : "string",
                "format" : "binary"
              }
            },
            "application/rdf+json" : {
              "schema" : {
                "type" : "string",
                "format" : "binary"
              }
            }
          },
          "description" : "OLGA input parameters"
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "olgaInput" : {
        "type" : "object",
        "required" : [ "name", "code", "library" ],
        "properties" : {
          "code" : {
            "type" : "string",
            "description" : "generated code cs, java, or py",
            "enum" : [ "cs", "java", "py" ],
            "maximum" : 1
          },
          "name" : {
            "type" : "string",
            "description" : "desired generated library name",
            "example" : "Saref",
            "maximum" : 1
          },
          "library" : {
            "type" : "string",
            "description" : "dependency on a library such as trinity, rdf4J, rdfalchemy",
            "enum" : [ "trinity", "rdf4J", "rdfalchemy" ],
            "maximum" : 1
          },
          "preserve" : {
            "type" : "boolean",
            "description" : "(Optional) relies on the Ontology URI when generating folder structure. When two or more ontologies are given as an input to OLGA it is preferable to use \"-preserve\" option to avoid overwriting the identical names entities"
          },
          "version" : {
            "type" : "string",
            "description" : "(Optional) <major>.<minor>.<build>.<revision>. By default OLGA assigns the Ontology version to the generated library. When the version is missing, OLGA version is assigned to the generated library. This option allows the user to force the version of the generated library"
          },
          "partial" : {
            "type" : "boolean",
            "description" : "(Optional) Relevant for C_# code generation only, appends the keyword partial to the generated code"
          }
        }
      }
    }
  }
}
```

**Comment by stevehu** [comment]
I think the error message is due to the security is not defined. Here is the best practices document for OpenAPI 3.0 specification. Let me know if there is still issue after adding the security definitions. 

https://www.networknt.com/development/best-practices/openapi3/

**Comment by siom79** [comment]
I have converted the openapi file to json:
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Example API",
    "description": "The API of the Example service.",
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "/example/v1"
    }
  ],
  "components": {
    "schemas": {
      "Person": {
        "properties": {
          "personId": {
            "type": "string"
          }
        },
        "required": [
          "personId"
        ]
      }
    }
  },
  "paths": {
    "/persons/{personId}": {
      "get": {
        "summary": "Returns the requested person.",
        "description": "Returns the person given by the parameter personId.",
        "parameters": [
          {
            "name": "personId",
            "in": "path",
            "required": true,
            "description": "ID of the person",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the requested person.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Person"
                }
              }
            }
          },
          "400": {
            "description": "The specified ID is invalid."
          },
          "404": {
            "description": "A person with the specified ID was not found."
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      }
    }
  }
}
```
This results in the following error message:
```
com.networknt.oas.OpenApiParser$SwaggerParserException: Failed to parse spec as JSON or YAML
        at com.networknt.oas.OpenApiParser.parse(OpenApiParser.java:43)
        at com.networknt.oas.OpenApiParser.parse(OpenApiParser.java:32)
        at com.networknt.codegen.rest.OpenApiGenerator.getOperationList(OpenApiGenerator.java:427)
        at com.networknt.codegen.rest.OpenApiGenerator.generate(OpenApiGenerator.java:136)
        at com.networknt.codegen.Cli.run(Cli.java:98)
        at com.networknt.codegen.Cli.main(Cli.java:50)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('n' (code 110)): was expecting double-quote to start field name
 at [Source: (String)"{"components":{"schemas": {
      "Person": {
        "properties": {
          "personId": {
            "type": "string"
          }
        },
        "required": [
          "personId"
        ]
      }
    }},"servers": [
    {
      "url": "/example/v1"
    }
  ],"openapi": "3.0.0","paths":{"/health":{"get":{"responses":{"200":{"description":"successful operation"}},"parameters":[]}},"/persons/{personId}": {
      "get": {
        "summary": "Returns the requested person.",
        "descri"[truncated 1194 chars]; line: 53, column: 44]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1757)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:907)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:246)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:434)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4044)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2539)
        at com.networknt.oas.jsonoverlay.JsonLoader.loadString(JsonLoader.java:49)
        at com.networknt.oas.OpenApiParser.parse(OpenApiParser.java:38)
        ... 5 more
```
Line 53, column 44 is ``},``. Any ideas?

**Comment by siom79** [comment]
Even if I add security, I get a similiar error message:
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Example API",
    "description": "The API of the Example service.",
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "/example/v1"
    }
  ],
  "components": {
    "schemas": {
      "Person": {
        "properties": {
          "personId": {
            "type": "string"
          }
        },
        "required": [
          "personId"
        ]
      }
    },
    "securitySchemes": {
      "BasicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "security": [
    {
      "BasicAuth": []
    }
  ],
  "paths": {
    "/persons/{personId}": {
      "get": {
        "summary": "Returns the requested person.",
        "description": "Returns the person given by the parameter personId.",
        "parameters": [
          {
            "name": "personId",
            "in": "path",
            "required": true,
            "description": "ID of the person",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the requested person.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Person"
                }
              }
            }
          },
          "400": {
            "description": "The specified ID is invalid."
          },
          "404": {
            "description": "A person with the specified ID was not found."
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      }
    }
  }
}
```
Error message:
```
08:40:51.129 [main] INFO com.fizzed.rocker.runtime.RockerRuntime - Rocker template reloading not activated
com.networknt.oas.OpenApiParser$SwaggerParserException: Failed to parse spec as JSON or YAML
        at com.networknt.oas.OpenApiParser.parse(OpenApiParser.java:43)
        at com.networknt.oas.OpenApiParser.parse(OpenApiParser.java:32)
        at com.networknt.codegen.rest.OpenApiGenerator.getOperationList(OpenApiGenerator.java:427)
        at com.networknt.codegen.rest.OpenApiGenerator.generate(OpenApiGenerator.java:136)
        at com.networknt.codegen.Cli.run(Cli.java:98)
        at com.networknt.codegen.Cli.main(Cli.java:50)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('n' (code 110)): was expecting double-quote to start field name
 at [Source: (String)"{"components":{"securitySchemes":{"BasicAuth":{"type": "http","scheme": "basic"}},"schemas": {
      "Person": {
        "properties": {
          "personId": {
            "type": "string"
          }
        },
        "required": [
          "personId"
        ]
      }
    }},"security": [
    {
      "BasicAuth": []
    }
  ],"servers": [
    {
      "url": "/example/v1"
    }
  ],"openapi": "3.0.0","paths":{"/health":{"get":{"responses":{"200":{"description":"successful operation"}},"param"[truncated 1313 chars]; line: 57, column: 44]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1757)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:907)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:246)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:434)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4044)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2539)
        at com.networknt.oas.jsonoverlay.JsonLoader.loadString(JsonLoader.java:49)
        at com.networknt.oas.OpenApiParser.parse(OpenApiParser.java:38)
        ... 5 more
```

**Comment by stevehu** [comment]
I am sorry that I didn't make it clear. The current version only supports OAuth 2.0 security. I will update the generator to support basic authentication. Let's keep this issue open until basic auth is resolved. Thanks.

**Comment by siom79** [comment]
Thanks for the prompt answer. Indeed, with OAuth it works:
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Example API",
    "description": "The API of the Example service.",
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "http://127.0.0.1:8080/example/v1/"
    }
  ],
  "components": {
    "schemas": {
      "Person": {
        "properties": {
          "personId": {
            "type": "string"
          }
        },
        "required": [
          "personId"
        ]
      }
    },
    "securitySchemes": {
      "iprs_auth": {
        "type": "oauth2",
        "description": "This API uses OAuth 2 with the client credential grant flow.",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://localhost:6882/token",
            "scopes": {
              "write": "Write access"
            }
          }
        }
      }
    }
  },
  "paths": {
    "/persons/{personId}": {
      "get": {
        "summary": "Returns the requested person.",
        "description": "Returns the person given by the parameter personId.",
        "parameters": [
          {
            "name": "personId",
            "in": "path",
            "required": true,
            "description": "ID of the person",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the requested person.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Person"
                }
              }
            }
          },
          "400": {
            "description": "The specified ID is invalid."
          },
          "404": {
            "description": "A person with the specified ID was not found."
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      }
    }
  }
}
```
