### ISSUE TITLE
NullPointerException when enableParamDescription is true

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#284]
We have reported from our users that the parameter description generation sometimes gets an NPE. It works after disabling it in the config.json file.

```
Exception in thread "main" com.fizzed.rocker.RenderingException: templates/rest/handler.rocker.raw [line 18:24]: NullPointerException in render
	at com.fizzed.rocker.runtime.DefaultRockerTemplate.__render(DefaultRockerTemplate.java:105)
	at com.fizzed.rocker.runtime.DefaultRockerModel.doRender(DefaultRockerModel.java:67)
	at com.fizzed.rocker.runtime.DefaultRockerModel.render(DefaultRockerModel.java:42)
	at com.networknt.codegen.Generator.transfer(Generator.java:88)
	at com.networknt.codegen.rest.OpenApiGenerator.generate(OpenApiGenerator.java:383)
	at com.networknt.codegen.Cli.run(Cli.java:104)
	at com.networknt.codegen.Cli.main(Cli.java:55)
Caused by: java.lang.NullPointerException
	at templates.rest.handler$Template.lambda$__doRender$1(handler.java:250)
	at com.fizzed.rocker.runtime.Java8Iterator.forEach(Java8Iterator.java:68)
	at templates.rest.handler$Template.__doRender(handler.java:219)
	at com.fizzed.rocker.runtime.DefaultRockerTemplate.__render(DefaultRockerTemplate.java:98)
	... 6 more

```

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NullPointerException when enableParamDescription is true](https://trello.com/c/4PzMvCJ8/165-nullpointerexception-when-enableparamdescription-is-true)
