### ISSUE TITLE
NPE when generate project with json as query parameter

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#298]
This is related to an [issue](https://github.com/networknt/light-rest-4j/issues/67) in light-rest-4j. I have put the provided testproject.yaml and config.json into the model-config and try to generate a test project to test the solution and the following error occurs. 

The model-config can be found at https://github.com/networknt/model-config/tree/master/rest/openapi/json-query-param

I run the codegen from the master branch. 

```
cd ~/networknt
rm -rf light-example-4j/rest/openapi/json-query-param
java -jar light-codegen/codegen-cli/target/codegen-cli.jar -f openapi -o light-example-4j/rest/openapi/json-query-param -m model-config/rest/openapi/json-query-param/openapi.yaml -c model-config/rest/openapi/json-query-param/config.json
```
And here is the error. 

```
Exception in thread "main" java.lang.NullPointerException
	at com.networknt.codegen.rest.OpenApiGenerator.lambda$getOperationList$1(OpenApiGenerator.java:756)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.networknt.codegen.rest.OpenApiGenerator.getOperationList(OpenApiGenerator.java:757)
	at com.networknt.codegen.rest.OpenApiGenerator.generate(OpenApiGenerator.java:133)
	at com.networknt.codegen.Cli.run(Cli.java:104)
	at com.networknt.codegen.Cli.main(Cli.java:55)

```

**Comment by stevehu** [comment]
@dz-1 found that the specification is invalid although it passed the validation in the swagger-editor. After making the following change, the light-codegen generates the project. 

From 

```
      parameters:
          $ref: '#/components/schemas/TestObject'
```

To 

```
      parameters:
        - in: query
          name: TestObject
          schema: 
            $ref: '#/components/schemas/TestObject'
```
