### ISSUE TITLE
service running error caused by config.yml file

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-codegen#301]
run the new generated service API, got error:

Caused by: java.lang.ClassNotFoundException: ${config.decryptorClass:com.networknt.decrypt.AESDecryptor}
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.networknt.config.yml.DecryptConstructor.createDecryptor(DecryptConstructor.java:45)

The injection cannot pickup the default value in the config.yml file. It cannot be injected in the values.yml file as well:
decryptorClass: ${config.decryptorClass:com.networknt.decrypt.AESDecryptor}

**Comment by stevehu** [comment]
There is an additional issue with the config.yml file generation. The config.yml needs to be in the

  "generateEnvVars": {
    "generate": true,
    "skipArray": true,
    "skipMap": true,
    "exclude": [
      "handerl.yml",
      "values.yml",
      "config.yml"
    ]
  }

in the config.json file as the input for the light-codegen. This is not acceptable as existing users won't know to add this section correctly. We need somehow make it as a default. Or we can manually update the template instead of using the YAMLFileParameterizer class blindly.

**Comment by stevehu** [comment]
The generated config.yml decryptorClass is in the next line. Updated it to move into the same line.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [service running error caused by config.yml file](https://trello.com/c/YdtvgH2d/221-service-running-error-caused-by-configyml-file)
