### ISSUE TITLE
send example as response cause exception when generating with swagger

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-codegen#355]
send example as response cause exception when generating with swagger
Exception in thread "main" com.fizzed.rocker.RenderingException: templates/rest/handler.rocker.raw [line 26:9]: Index 1 out of bounds for length 1
	at com.fizzed.rocker.runtime.DefaultRockerTemplate.__render(DefaultRockerTemplate.java:105)
	at com.fizzed.rocker.runtime.DefaultRockerModel.doRender(DefaultRockerModel.java:67)
	at com.fizzed.rocker.runtime.DefaultRockerModel.render(DefaultRockerModel.java:42)
	at com.networknt.codegen.Generator.transfer(Generator.java:85)
	at com.networknt.codegen.rest.SwaggerGenerator.generate(SwaggerGenerator.java:292)
	at com.networknt.codegen.Cli.run(Cli.java:108)
	at com.networknt.codegen.Cli.main(Cli.java:56)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at templates.rest.handler$Template.__doRender(handler.java:361)
	at com.fizzed.rocker.runtime.DefaultRockerTemplate.__render(DefaultRockerTemplate.java:98)
	... 6 more

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [send example as response cause exception when generating with swagger](https://trello.com/c/9HQ1Cjj5/343-send-example-as-response-cause-exception-when-generating-with-swagger)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [send example as response cause exception when generating with swagger](https://trello.com/c/fex5pRoO/344-send-example-as-response-cause-exception-when-generating-with-swagger)
