### ISSUE TITLE
A runtime exception is thrown with oneOf in the specification

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#444]
I am generating code (light-codegen) for a large Open Banking specification and I get an error that does not look accurate.

The file is located here:
https://github.com/OpenBankingUK/read-write-api-specs/blob/master/dist/openapi/account-info-openapi.yaml

The error is as follows:

```
Unable to load config 'values' with extension yml, yaml and json from external config, application config and module config. Please ignore this message if you are sure that your application is not using this config file.
Exception in thread "main" java.lang.RuntimeException: Cannot find the type of "OBScheduledPayment3" in #/components/schemas/ of the specification file.
	at com.networknt.codegen.rest.OpenApiGenerator.loadModel(OpenApiGenerator.java:876)
	at com.networknt.codegen.rest.OpenApiGenerator.generate(OpenApiGenerator.java:228)
	at com.networknt.codegen.Cli.run(Cli.java:108)
	at com.networknt.codegen.Cli.main(Cli.java:56)
```

Yet... I know that OBSchedulePayment3 does exist in components/schemas...

**Comment by stevehu** [comment]
There are two issues that need to be addressed: 

1. As there is no type available in the oneOf, we cannot throw the exception blindly. We need to ensure that type is null and isAbstractClass is false to throw the exception. 

```
    OBScheduledPayment3:
      oneOf:
        - $ref: '#/components/schemas/OBScheduledPayment3Basic'
        - $ref: '#/components/schemas/OBScheduledPayment3Detail'

```

2. The generated code for the oneOf should extend from the ref object not the parent. As the parent class doesn't exist. 

To reproduce the issue, I have copied a simply account-info.yaml to the test resource and created a test case.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A runtime exception is thrown with oneOf in the specification light-codegen master](https://trello.com/c/hQZ9DBit/712-a-runtime-exception-is-thrown-with-oneof-in-the-specification-light-codegen-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A runtime exception is thrown with oneOf in the specification light-codegen 1.6.x](https://trello.com/c/eWrWZq1D/713-a-runtime-exception-is-thrown-with-oneof-in-the-specification-light-codegen-16x)
