### ISSUE TITLE
AWS Lambda Jackson Reflection

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-codegen#521]
### Issue
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:404)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4110)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3413)
	at com.networknt.petstore.handler.BusinessHandler.handleRequest(BusinessHandler.java:32)
	at com.networknt.petstore.handler.App.handleRequest(App.java:20)
	at com.networknt.petstore.handler.App.handleRequest(App.java:16)
	at com.networknt.aws.lambda.Runtime.main(Runtime.java:43)
```
### Reason
Because of GraalVM's AOT feature, you need to explicitly declaire the reflection Object in config.
Related article: https://javalin.io/2018/09/27/javalin-graalvm-example.html

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AWS Lambda Jackson Reflection light-codegen master](https://trello.com/c/MQ1MH6tu/935-aws-lambda-jackson-reflection-light-codegen-master)
