### ISSUE TITLE
codegen-web will be compiled as a thin jar not a fat jar

### ISSUE THREAD

**Issue by stevehu** [networknt/light-codegen#56]
As it is a light-hybrid-4j service and it will be run within a light-hybrid-4j server which can be found at https://github.com/networknt/light-portal/tree/master/hybrid-server

The compiled jar has been copied and checked in light-portal/hybrid-service folder. Please read light-portal/hybrid-server readme for instructions on how to start the server along with all the services.

**Comment by NicholasAzar** [comment]
@stevehu Do preexisting hybrid servers need to be regenerated when using the updated thin jar of codegen-web?

**Comment by stevehu** [comment]
No need to regenerate the server as all dependencies are there all ready. You just need to drop the new service jar to replace the old one. This is the location for the codegen-web. 

https://github.com/networknt/light-portal/tree/master/hybrid-service

**Comment by NicholasAzar** [comment]
@stevehu I think this change broke codegen-web integration with light-hybrid.
When bringing up the server i get the following error:
```Exception in thread "main" java.lang.NoClassDefFoundError: com/networknt/codegen/FrameworkRegistry
	at com.networknt.codegen.handler.FrameworkListHandler.<clinit>(FrameworkListHandler.java:28)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.networknt.rpc.router.RpcStartupHookProvider.onStartup(RpcStartupHookProvider.java:45)
	at com.networknt.server.Server.start(Server.java:112)
	at com.networknt.server.Server.main(Server.java:101)
Caused by: java.lang.ClassNotFoundException: com.networknt.codegen.FrameworkRegistry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more```

**Comment by stevehu** [comment]
@NicholasAzar I have tried both commands in the README.md and both are working fine. I think you are trying to start the service as a standalone server. Try the command line in the following README and let me know if there are still errors. Thanks.

https://github.com/networknt/light-portal/tree/master/hybrid-server

**Comment by NicholasAzar** [comment]
Clearly no longer an issue 😄
