### ISSUE TITLE
out of bound error when security empty

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-codegen#564]
in sepc, when use 
```
security: []
```
it will cause:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at com.networknt.jsonoverlay.ListOverlay.get(ListOverlay.java:113)
	at com.networknt.jsonoverlay.PropertiesOverlay._get(PropertiesOverlay.java:109)
	at com.networknt.jsonoverlay.PropertiesOverlay._get(PropertiesOverlay.java:103)
	at com.networknt.oas.model.impl.OperationImpl.getSecurityRequirement(OperationImpl.java:459)
	at com.networknt.codegen.rest.OpenApiGenerator.getScopes(OpenApiGenerator.java:281)
	at com.networknt.codegen.rest.OpenApiGenerator.getOperationList(OpenApiGenerator.java:335)
	at ca.sunlife.eadp.codegen.SunlifeOpenApiLightGenerator.generate(SunlifeOpenApiLightGenerator.java:101)
	at ca.sunlife.eadp.codegen.cli.Cli.run(Cli.java:142)
	at ca.sunlife.eadp.codegen.cli.Cli.main(Cli.java:69)
```

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [out of bound error when security empty light-codegen master](https://trello.com/c/i42j4rIS/1011-out-of-bound-error-when-security-empty-light-codegen-master)
